// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Data;

namespace Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20200821183226_DataSeed-3")]
    partial class DataSeed3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Models.Company", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("4c2502a4-5ca6-4fe4-bbb8-ac1e00ef9e85"),
                            Address = "253 Fulton Circle Menasha, WI 54952",
                            Name = "Ecstatic Systems",
                            RegDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "431-393-0117"
                        },
                        new
                        {
                            Uid = new Guid("51ec904b-457d-4bca-8ff1-ac1e00ef9e85"),
                            Address = "55 Shub Farm Court Yuma, AZ 85365",
                            Name = "Red Limited",
                            RegDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "887-738-4272"
                        },
                        new
                        {
                            Uid = new Guid("ecb80419-3bdc-4d53-94e5-ac1e00ef9e85"),
                            Address = "8863 Howard Court Traverse City, MI 49684",
                            Name = "Primal Electronics",
                            RegDate = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "909-467-1181"
                        },
                        new
                        {
                            Uid = new Guid("0362d963-d06c-4277-a617-ac1e00ef9e85"),
                            Address = "813 Pheasant Street Huntley, IL 60142",
                            Name = "Surprisystems",
                            RegDate = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "558-663-2657"
                        },
                        new
                        {
                            Uid = new Guid("24a54cf1-0b4f-48f9-ad12-ac1e00ef9e85"),
                            Address = "5 Boston St. Patchogue, NY 11772",
                            Name = "Gorillacoustics",
                            RegDate = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "208-652-0972"
                        },
                        new
                        {
                            Uid = new Guid("c13e484f-54aa-4a48-86ef-ac1e00ef9e85"),
                            Address = "39 Jockey Hollow St. Passaic, NJ 07055",
                            Name = "Silver Linetworks",
                            RegDate = new DateTime(2019, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "754-934-6607"
                        },
                        new
                        {
                            Uid = new Guid("67fe9128-7f6b-47d5-b792-ac1e00ef9e85"),
                            Address = "8 Main St. Bridgeton, NJ 08302",
                            Name = "Dwarfoods",
                            RegDate = new DateTime(2019, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "428-213-6913"
                        },
                        new
                        {
                            Uid = new Guid("342a6e42-f0f7-4438-9a31-ac1e00ef9e85"),
                            Address = "9801 Mammoth Drive Winston Salem, NC 27103",
                            Name = "Greenaid",
                            RegDate = new DateTime(2019, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "453-539-9934"
                        },
                        new
                        {
                            Uid = new Guid("c85e1c94-ea2f-4382-8953-ac1e00ef9e85"),
                            Address = "49 Talbot Street Stroudsburg, PA 18360",
                            Name = "Squidwood",
                            RegDate = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "925-925-3730"
                        },
                        new
                        {
                            Uid = new Guid("ce591c66-7532-4a43-bf4c-ac1e00ef9e85"),
                            Address = "7566 Hawthorne Drive Port Chester, NY 10573",
                            Name = "Thunderwares",
                            RegDate = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "922-481-4794"
                        },
                        new
                        {
                            Uid = new Guid("1e6cbbf5-9006-4646-a497-ac1e00ef9e85"),
                            Address = "9337 East Dr. Meadville, PA 16335",
                            Name = "Tundra Brews",
                            RegDate = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "771-896-0645"
                        },
                        new
                        {
                            Uid = new Guid("e3182add-c4ff-4f4a-bff8-ac1e00ef9e85"),
                            Address = "14 Academy Street Arlington, MA 02474",
                            Name = "Angel Systems",
                            RegDate = new DateTime(2019, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "374-323-7205"
                        },
                        new
                        {
                            Uid = new Guid("ef93f3e3-9129-4f87-bb34-ac1e00ef9e85"),
                            Address = "8959 Pennsylvania Court Hoboken, NJ 07030",
                            Name = "Ecstatic Enterprises",
                            RegDate = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "992-452-6822"
                        },
                        new
                        {
                            Uid = new Guid("5b39a75d-4185-49b8-b52b-ac1e00ef9e85"),
                            Address = "8501 James St. Southampton, PA 18966",
                            Name = "Starecords",
                            RegDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "798-594-7742"
                        },
                        new
                        {
                            Uid = new Guid("3b9ee833-513b-4c49-824d-ac1e00ef9e85"),
                            Address = "9022 Branch St. Montgomery Village, MD 20886",
                            Name = "Apexi",
                            RegDate = new DateTime(2020, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "350-813-1923"
                        },
                        new
                        {
                            Uid = new Guid("46f93679-0ab1-4088-835d-ac1e00ef9e85"),
                            Address = "100 Old Oxford Ave. Norwich, CT 06360",
                            Name = "Galerprises",
                            RegDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "520-872-8810"
                        },
                        new
                        {
                            Uid = new Guid("7ac4074f-7b40-4958-a452-ac1e00ef9e85"),
                            Address = "443 Gates Avenue Memphis, TN 38106",
                            Name = "Quaductions",
                            RegDate = new DateTime(2020, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "799-500-7874"
                        },
                        new
                        {
                            Uid = new Guid("e7949576-0ef6-41df-aab3-ac1e00ef9e85"),
                            Address = "85 Marlborough Dr. Zeeland, MI 49464",
                            Name = "Wavemedia",
                            RegDate = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "773-728-4669"
                        },
                        new
                        {
                            Uid = new Guid("a6031a30-2249-4a09-9597-ac1e00ef9e85"),
                            Address = "890 Wood Street Baltimore, MD 21206",
                            Name = "Pixywater",
                            RegDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "244-916-5331"
                        },
                        new
                        {
                            Uid = new Guid("100caa03-a28e-4a81-840b-ac1e00ef9e85"),
                            Address = "39 Tarkiln Hill St. West Hempstead, NY 11552",
                            Name = "Hoglight",
                            RegDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "392-458-6631"
                        },
                        new
                        {
                            Uid = new Guid("4b34cfda-fbb9-46b8-94d3-ac1e00ef9e85"),
                            Address = "8638 Santa Clara St. Yuba City, CA 95993",
                            Name = "Twilight Corporation",
                            RegDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "551-996-8865"
                        },
                        new
                        {
                            Uid = new Guid("ce5db689-d082-4d71-9f83-ac1e00ef9e85"),
                            Address = "506 South Gregory Lane Cumming, GA 30040",
                            Name = "Silver",
                            RegDate = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "467-454-5805"
                        },
                        new
                        {
                            Uid = new Guid("05156605-7cad-42c5-a0d4-ac1e00ef9e85"),
                            Address = "2 Howard Ave. Germantown, MD 20874",
                            Name = "Red Security",
                            RegDate = new DateTime(2020, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "931-970-0832"
                        },
                        new
                        {
                            Uid = new Guid("a4bdb1f1-85e7-49f1-b490-ac1e00ef9e85"),
                            Address = "580 N. Liberty Dr. Orange Park, FL 32065",
                            Name = "Chiefoods",
                            RegDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "975-663-2423"
                        },
                        new
                        {
                            Uid = new Guid("4d7750b4-7211-45a4-8a1c-ac1e00ef9e85"),
                            Address = "9459 North Mill Ave. Roanoke Rapids, NC 27870",
                            Name = "Essensecurity",
                            RegDate = new DateTime(2020, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "966-722-2521"
                        },
                        new
                        {
                            Uid = new Guid("847e1699-e822-4a9c-95bf-ac1e00ef9e85"),
                            Address = "543 White Drive New Bedford, MA 02740",
                            Name = "Elitelligence",
                            RegDate = new DateTime(2018, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "606-752-7843"
                        },
                        new
                        {
                            Uid = new Guid("77e94f03-0cb6-4606-bdd5-ac1e00ef9e85"),
                            Address = "96 Armstrong Lane Cary, NC 27511",
                            Name = "Daydreamotors",
                            RegDate = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "838-383-3934"
                        },
                        new
                        {
                            Uid = new Guid("e93fbb3f-55b2-47bd-91c3-ac1e00ef9e85"),
                            Address = "8561 Glen Eagles Circle Natick, MA 01760",
                            Name = "Heartstone",
                            RegDate = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "509-760-3953"
                        },
                        new
                        {
                            Uid = new Guid("fe1a2c64-7e7a-4156-a064-ac1e00ef9e85"),
                            Address = "37 East Logan Lane Eugene, OR 97402",
                            Name = "Lagoonmaster",
                            RegDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "827-418-5289"
                        },
                        new
                        {
                            Uid = new Guid("90ad9c4b-2a45-432b-a41b-ac1e00ef9e85"),
                            Address = "53 Hickory Court Klamath Falls, OR 97603",
                            Name = "Shadecloud",
                            RegDate = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "629-202-6953"
                        },
                        new
                        {
                            Uid = new Guid("bcd332d7-2853-4d81-bf52-ac1e00ef9e85"),
                            Address = "8352 Marsh St. Indian Trail, NC 28079",
                            Name = "Pinnacle Aviation",
                            RegDate = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "937-490-6629"
                        },
                        new
                        {
                            Uid = new Guid("f17d76cc-896c-4bca-9910-ac1e00ef9e85"),
                            Address = "9825 Pilgrim Ave. Ontario, CA 91762",
                            Name = "Neptune Solutions",
                            RegDate = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "713-210-5080"
                        },
                        new
                        {
                            Uid = new Guid("faaaff9a-676f-4d29-b950-ac1e00ef9e85"),
                            Address = "2 Fordham Drive Merrick, NY 11566",
                            Name = "Night Networks",
                            RegDate = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "865-503-5762"
                        },
                        new
                        {
                            Uid = new Guid("0186e863-5aaf-4495-a2fe-ac1e00ef9e85"),
                            Address = "292 Jones Lane Lanham, MD 20706",
                            Name = "Forestics",
                            RegDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "845-892-1111"
                        },
                        new
                        {
                            Uid = new Guid("01e323df-7df1-4b9b-94ee-ac1e00ef9e85"),
                            Address = "91 Amerige Ave. Muscatine, IA 52761",
                            Name = "Bearings",
                            RegDate = new DateTime(2019, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "984-496-5436"
                        },
                        new
                        {
                            Uid = new Guid("78f46107-e0bf-4cb6-ab48-ac1e00ef9e85"),
                            Address = "788B Miles Ave. Fairport, NY 14450",
                            Name = "Mermedia",
                            RegDate = new DateTime(2019, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "905-246-2186"
                        },
                        new
                        {
                            Uid = new Guid("b02ef1c2-b891-4c67-a1cd-ac1e00ef9e85"),
                            Address = "8403 Goldfield Ave. King Of Prussia, PA 19406",
                            Name = "Fairiprises",
                            RegDate = new DateTime(2019, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "519-259-6669"
                        },
                        new
                        {
                            Uid = new Guid("dcb01214-1751-4f52-bc80-ac1e00ef9e85"),
                            Address = "7507 Wakehurst Avenue Murfreesboro, TN 37128",
                            Name = "Mountaintime",
                            RegDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "801-871-4863"
                        },
                        new
                        {
                            Uid = new Guid("fd09c766-a653-408c-8ab3-ac1e00ef9e85"),
                            Address = "153 Old Lancaster Street Princeton, NJ 08540",
                            Name = "Fireworth",
                            RegDate = new DateTime(2019, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "264-712-5689"
                        },
                        new
                        {
                            Uid = new Guid("055d5c98-254e-4643-91e1-ac1e00ef9e85"),
                            Address = "108 Canterbury Avenue Reston, VA 20191",
                            Name = "Cloudworld",
                            RegDate = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "314-535-5117"
                        },
                        new
                        {
                            Uid = new Guid("352ead58-e1da-4749-b0fd-ac1e00ef9e85"),
                            Address = "932 Locust Ave. Minot, ND 58701",
                            Name = "Alp Arts",
                            RegDate = new DateTime(2020, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "542-361-0307"
                        },
                        new
                        {
                            Uid = new Guid("cfcff273-3454-4c08-81b9-ac1e00ef9e85"),
                            Address = "47 Glenridge Ave. Tupelo, MS 38801",
                            Name = "Timber Security",
                            RegDate = new DateTime(2020, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "744-230-2997"
                        });
                });

            modelBuilder.Entity("Test.Models.Invoice", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CompanyUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.HasIndex("CompanyUid");

                    b.ToTable("Invoice");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("3ebd9cfe-44ae-4f0b-9324-ac1e00ef9e85"),
                            CompanyUid = new Guid("4c2502a4-5ca6-4fe4-bbb8-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-23-00-01",
                            Total = 34300.040000000001,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("6776cb74-9d4d-4d28-9d40-ac1e00ef9e85"),
                            CompanyUid = new Guid("51ec904b-457d-4bca-8ff1-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-28-00-02",
                            Total = 15690.59,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("9e7f365b-a6a4-479f-bf7b-ac1e00ef9e85"),
                            CompanyUid = new Guid("ecb80419-3bdc-4d53-94e5-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-31-00-03",
                            Total = 298.36000000000001,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("70fa201e-bbe0-49c9-a1b4-ac1e00ef9e85"),
                            CompanyUid = new Guid("0362d963-d06c-4277-a617-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-02-21-00-04",
                            Total = 1431.4300000000001,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("866adf7b-d273-4d4a-bff5-ac1e00ef9e85"),
                            CompanyUid = new Guid("24a54cf1-0b4f-48f9-ad12-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-03-31-00-05",
                            Total = 18186.209999999999,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("3dd0d705-d696-4140-9db0-ac1e00ef9e85"),
                            CompanyUid = new Guid("c13e484f-54aa-4a48-86ef-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-04-17-00-06",
                            Total = 4909.3299999999999,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("2858c955-ee84-42b8-b999-ac1e00ef9e85"),
                            CompanyUid = new Guid("67fe9128-7f6b-47d5-b792-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-15-00-07",
                            Total = 39931.110000000001,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("41e77c18-a195-4ff9-aeff-ac1e00ef9e85"),
                            CompanyUid = new Guid("342a6e42-f0f7-4438-9a31-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-21-00-08",
                            Total = 28254.93,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("d2496cab-496b-44ff-b6d9-ac1e00ef9e85"),
                            CompanyUid = new Guid("c85e1c94-ea2f-4382-8953-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-22-00-09",
                            Total = 44787.620000000003,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("8c920768-2e00-45ab-b8f3-ac1e00ef9e85"),
                            CompanyUid = new Guid("ce591c66-7532-4a43-bf4c-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-26-00-10",
                            Total = 22502.970000000001,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("726b0ed2-c4b0-4e9e-9dd4-ac1e00ef9e85"),
                            CompanyUid = new Guid("1e6cbbf5-9006-4646-a497-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-01-00-11",
                            Total = 4945.6999999999998,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("9cb82b83-c8f6-4ac9-8abe-ac1e00ef9e85"),
                            CompanyUid = new Guid("e3182add-c4ff-4f4a-bff8-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-03-00-12",
                            Total = 36277.519999999997,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("ddcd274d-d937-41fe-a4e9-ac1e00ef9e85"),
                            CompanyUid = new Guid("ef93f3e3-9129-4f87-bb34-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-11-00-13",
                            Total = 23971.299999999999,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("714492f5-b04c-4fd9-9fd3-ac1e00ef9e85"),
                            CompanyUid = new Guid("5b39a75d-4185-49b8-b52b-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-23-00-14",
                            Total = 46565.209999999999,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("876bea66-b69b-44da-8d74-ac1e00ef9e85"),
                            CompanyUid = new Guid("3b9ee833-513b-4c49-824d-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-03-00-15",
                            Total = 38232.68,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("e2ddc025-ebb9-43a9-b1c8-ac1e00ef9e85"),
                            CompanyUid = new Guid("46f93679-0ab1-4088-835d-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-24-00-16",
                            Total = 27786.68,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("f7fda580-0efc-4bc0-b4f7-ac1e00ef9e85"),
                            CompanyUid = new Guid("7ac4074f-7b40-4958-a452-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-08-00-17",
                            Total = 22732.68,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("3c945306-f185-47fe-9590-ac1e00ef9e85"),
                            CompanyUid = new Guid("e7949576-0ef6-41df-aab3-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-22-00-18",
                            Total = 43822.839999999997,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("e5d029e5-4060-498e-a560-ac1e00ef9e85"),
                            CompanyUid = new Guid("a6031a30-2249-4a09-9597-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-10-01-00-19",
                            Total = 15328.68,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("bf08651d-5647-4488-bcad-ac1e00ef9e85"),
                            CompanyUid = new Guid("100caa03-a28e-4a81-840b-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-10-22-00-20",
                            Total = 48152.279999999999,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("264ae9e2-40f4-4f2b-9888-ac1e00ef9e85"),
                            CompanyUid = new Guid("4b34cfda-fbb9-46b8-94d3-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-11-26-00-21",
                            Total = 14065.1,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("5f378a9b-355c-411a-85c7-ac1e00ef9e85"),
                            CompanyUid = new Guid("ce5db689-d082-4d71-9f83-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-11-27-00-22",
                            Total = 37993.709999999999,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("7420a9e4-e8e4-4bc7-a1ff-ac1e00ef9e85"),
                            CompanyUid = new Guid("05156605-7cad-42c5-a0d4-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-11-30-00-23",
                            Total = 38244.32,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("1b37784f-6d11-4c3c-a6cd-ac1e00ef9e85"),
                            CompanyUid = new Guid("a4bdb1f1-85e7-49f1-b490-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-12-02-00-24",
                            Total = 27489.400000000001,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("f2498a05-e0c4-4a73-866c-ac1e00ef9e85"),
                            CompanyUid = new Guid("4d7750b4-7211-45a4-8a1c-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-12-22-00-25",
                            Total = 14378.530000000001,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("4437afd7-e54e-4e03-92f2-ac1e00ef9e85"),
                            CompanyUid = new Guid("847e1699-e822-4a9c-95bf-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-31-00-26",
                            Total = 45954.989999999998,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("44527b90-4b92-428d-af1d-ac1e00ef9e85"),
                            CompanyUid = new Guid("77e94f03-0cb6-4606-bdd5-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-02-06-00-27",
                            Total = 47950.589999999997,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("0a797f86-1dc5-4697-a05e-ac1e00ef9e85"),
                            CompanyUid = new Guid("e93fbb3f-55b2-47bd-91c3-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-02-21-00-28",
                            Total = 15495.889999999999,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("ebb5bd5f-18de-41e5-a0aa-ac1e00ef9e85"),
                            CompanyUid = new Guid("fe1a2c64-7e7a-4156-a064-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-03-23-00-29",
                            Total = 25963.68,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("14a72205-ecbc-4d04-b91c-ac1e00ef9e85"),
                            CompanyUid = new Guid("90ad9c4b-2a45-432b-a41b-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-04-17-00-30",
                            Total = 27774.66,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("1c382005-3d25-4c65-bbde-ac1e00ef9e85"),
                            CompanyUid = new Guid("bcd332d7-2853-4d81-bf52-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-01-00-31",
                            Total = 36187.620000000003,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("8b253f5c-6194-4a5e-8f5b-ac1e00ef9e85"),
                            CompanyUid = new Guid("f17d76cc-896c-4bca-9910-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-29-00-32",
                            Total = 29825.919999999998,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("c96848e1-6716-4b5d-baaf-ac1e00ef9e85"),
                            CompanyUid = new Guid("faaaff9a-676f-4d29-b950-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-02-00-33",
                            Total = 4298.6300000000001,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("4ea5e94d-23c0-497d-b4f6-ac1e00ef9e85"),
                            CompanyUid = new Guid("0186e863-5aaf-4495-a2fe-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-06-00-34",
                            Total = 43305.220000000001,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("1a109f4b-19b1-4968-b4d3-ac1e00ef9e85"),
                            CompanyUid = new Guid("01e323df-7df1-4b9b-94ee-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-15-00-35",
                            Total = 46484.260000000002,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("b11142e9-f643-4ef9-a163-ac1e00ef9e85"),
                            CompanyUid = new Guid("78f46107-e0bf-4cb6-ab48-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-20-00-36",
                            Total = 47141.389999999999,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("80a80dec-490c-4fa0-84d8-ac1e00ef9e85"),
                            CompanyUid = new Guid("b02ef1c2-b891-4c67-a1cd-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-23-00-37",
                            Total = 2787.27,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("29648e71-eb69-40fb-8bd9-ac1e00ef9e85"),
                            CompanyUid = new Guid("dcb01214-1751-4f52-bc80-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-24-00-38",
                            Total = 49818.980000000003,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("6a3f7141-7aa2-42f6-8de7-ac1e00ef9e85"),
                            CompanyUid = new Guid("fd09c766-a653-408c-8ab3-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-05-00-39",
                            Total = 45908.629999999997,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("6e2b4010-5396-4b66-a8a1-ac1e00ef9e85"),
                            CompanyUid = new Guid("055d5c98-254e-4643-91e1-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-27-00-40",
                            Total = 18576.209999999999,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("b6064917-2cc0-4db1-b318-ac1e00ef9e85"),
                            CompanyUid = new Guid("352ead58-e1da-4749-b0fd-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-02-00-41",
                            Total = 31128.419999999998,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("d2e044d2-5e5f-4d4a-9146-ac1e00ef9e85"),
                            CompanyUid = new Guid("cfcff273-3454-4c08-81b9-ac1e00ef9e85"),
                            InvDate = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-15-00-42",
                            Total = 14540.690000000001,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Test.Models.Invoice", b =>
                {
                    b.HasOne("Test.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
