// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Data;

namespace Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20200821182113_DataSeed-1")]
    partial class DataSeed1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Models.Company", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("3f3342a7-0bd7-44da-b5da-ac1e00ec8a8a"),
                            Address = "253 Fulton Circle Menasha, WI 54952",
                            Name = "Ecstatic Systems",
                            RegDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "431-393-0117"
                        },
                        new
                        {
                            Uid = new Guid("b8b866ab-728d-46a2-affe-ac1e00ec8a8a"),
                            Address = "55 Shub Farm Court Yuma, AZ 85365",
                            Name = "Red Limited",
                            RegDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "887-738-4272"
                        },
                        new
                        {
                            Uid = new Guid("be70744e-6732-4f03-89b7-ac1e00ec8a8a"),
                            Address = "8863 Howard Court Traverse City, MI 49684",
                            Name = "Primal Electronics",
                            RegDate = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "909-467-1181"
                        },
                        new
                        {
                            Uid = new Guid("c3c6ee6a-58d2-4ce0-9e9d-ac1e00ec8a8a"),
                            Address = "813 Pheasant Street Huntley, IL 60142",
                            Name = "Surprisystems",
                            RegDate = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "558-663-2657"
                        },
                        new
                        {
                            Uid = new Guid("6526d18f-2182-45c9-8aec-ac1e00ec8a8a"),
                            Address = "5 Boston St. Patchogue, NY 11772",
                            Name = "Gorillacoustics",
                            RegDate = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "208-652-0972"
                        },
                        new
                        {
                            Uid = new Guid("007b720a-ad72-4909-beb4-ac1e00ec8a8a"),
                            Address = "39 Jockey Hollow St. Passaic, NJ 07055",
                            Name = "Silver Linetworks",
                            RegDate = new DateTime(2019, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "754-934-6607"
                        },
                        new
                        {
                            Uid = new Guid("1089419e-3e69-4f00-812e-ac1e00ec8a8a"),
                            Address = "8 Main St. Bridgeton, NJ 08302",
                            Name = "Dwarfoods",
                            RegDate = new DateTime(2019, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "428-213-6913"
                        },
                        new
                        {
                            Uid = new Guid("5c88ad00-f764-4970-9b8f-ac1e00ec8a8a"),
                            Address = "9801 Mammoth Drive Winston Salem, NC 27103",
                            Name = "Greenaid",
                            RegDate = new DateTime(2019, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "453-539-9934"
                        },
                        new
                        {
                            Uid = new Guid("9a8dab0b-5210-4e55-945a-ac1e00ec8a8a"),
                            Address = "49 Talbot Street Stroudsburg, PA 18360",
                            Name = "Squidwood",
                            RegDate = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "925-925-3730"
                        },
                        new
                        {
                            Uid = new Guid("2f052098-a9dc-4454-9c01-ac1e00ec8a8a"),
                            Address = "7566 Hawthorne Drive Port Chester, NY 10573",
                            Name = "Thunderwares",
                            RegDate = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "922-481-4794"
                        },
                        new
                        {
                            Uid = new Guid("83539186-9cda-4ed2-9e27-ac1e00ec8a8a"),
                            Address = "9337 East Dr. Meadville, PA 16335",
                            Name = "Tundra Brews",
                            RegDate = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "771-896-0645"
                        },
                        new
                        {
                            Uid = new Guid("32c17641-e450-4e49-a877-ac1e00ec8a8a"),
                            Address = "14 Academy Street Arlington, MA 02474",
                            Name = "Angel Systems",
                            RegDate = new DateTime(2019, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "374-323-7205"
                        },
                        new
                        {
                            Uid = new Guid("08fb9f52-b72e-44b2-8e90-ac1e00ec8a8a"),
                            Address = "8959 Pennsylvania Court Hoboken, NJ 07030",
                            Name = "Ecstatic Enterprises",
                            RegDate = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "992-452-6822"
                        },
                        new
                        {
                            Uid = new Guid("2479d94e-5b9d-430f-9829-ac1e00ec8a8a"),
                            Address = "8501 James St. Southampton, PA 18966",
                            Name = "Starecords",
                            RegDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "798-594-7742"
                        },
                        new
                        {
                            Uid = new Guid("664b404b-3005-49a6-a9ea-ac1e00ec8a8a"),
                            Address = "9022 Branch St. Montgomery Village, MD 20886",
                            Name = "Apexi",
                            RegDate = new DateTime(2020, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "350-813-1923"
                        },
                        new
                        {
                            Uid = new Guid("c2208630-d4e7-471d-9f3c-ac1e00ec8a8a"),
                            Address = "100 Old Oxford Ave. Norwich, CT 06360",
                            Name = "Galerprises",
                            RegDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "520-872-8810"
                        },
                        new
                        {
                            Uid = new Guid("9260b2d5-1b95-4595-a330-ac1e00ec8a8a"),
                            Address = "443 Gates Avenue Memphis, TN 38106",
                            Name = "Quaductions",
                            RegDate = new DateTime(2020, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "799-500-7874"
                        },
                        new
                        {
                            Uid = new Guid("17a98816-d184-45b6-ab07-ac1e00ec8a8a"),
                            Address = "85 Marlborough Dr. Zeeland, MI 49464",
                            Name = "Wavemedia",
                            RegDate = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "773-728-4669"
                        },
                        new
                        {
                            Uid = new Guid("e0637e15-834d-4ba4-bcb9-ac1e00ec8a8a"),
                            Address = "890 Wood Street Baltimore, MD 21206",
                            Name = "Pixywater",
                            RegDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "244-916-5331"
                        },
                        new
                        {
                            Uid = new Guid("a2185710-7ec1-41a2-ad00-ac1e00ec8a8a"),
                            Address = "39 Tarkiln Hill St. West Hempstead, NY 11552",
                            Name = "Hoglight",
                            RegDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "392-458-6631"
                        },
                        new
                        {
                            Uid = new Guid("62b61f8d-1794-4b20-8c71-ac1e00ec8a8a"),
                            Address = "8638 Santa Clara St. Yuba City, CA 95993",
                            Name = "Twilight Corporation",
                            RegDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "551-996-8865"
                        },
                        new
                        {
                            Uid = new Guid("c39c20b0-7f4e-4ce8-9fa6-ac1e00ec8a8a"),
                            Address = "506 South Gregory Lane Cumming, GA 30040",
                            Name = "Silver",
                            RegDate = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "467-454-5805"
                        },
                        new
                        {
                            Uid = new Guid("5779ad22-48f4-4678-b4b6-ac1e00ec8a8a"),
                            Address = "2 Howard Ave. Germantown, MD 20874",
                            Name = "Red Security",
                            RegDate = new DateTime(2020, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "931-970-0832"
                        },
                        new
                        {
                            Uid = new Guid("8cfc1265-46b6-48ca-b7af-ac1e00ec8a8a"),
                            Address = "580 N. Liberty Dr. Orange Park, FL 32065",
                            Name = "Chiefoods",
                            RegDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "975-663-2423"
                        },
                        new
                        {
                            Uid = new Guid("536da5bf-d737-47be-b644-ac1e00ec8a8a"),
                            Address = "9459 North Mill Ave. Roanoke Rapids, NC 27870",
                            Name = "Essensecurity",
                            RegDate = new DateTime(2020, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "966-722-2521"
                        },
                        new
                        {
                            Uid = new Guid("7ac80ccb-d181-483d-bc95-ac1e00ec8a8a"),
                            Address = "543 White Drive New Bedford, MA 02740",
                            Name = "Elitelligence",
                            RegDate = new DateTime(2018, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "606-752-7843"
                        },
                        new
                        {
                            Uid = new Guid("ff8bd24f-1a07-4b9f-97fb-ac1e00ec8a8a"),
                            Address = "96 Armstrong Lane Cary, NC 27511",
                            Name = "Daydreamotors",
                            RegDate = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "838-383-3934"
                        },
                        new
                        {
                            Uid = new Guid("96ef9d31-5bb1-4941-be9d-ac1e00ec8a8a"),
                            Address = "8561 Glen Eagles Circle Natick, MA 01760",
                            Name = "Heartstone",
                            RegDate = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "509-760-3953"
                        },
                        new
                        {
                            Uid = new Guid("5e8f7378-6d23-4591-87bf-ac1e00ec8a8a"),
                            Address = "37 East Logan Lane Eugene, OR 97402",
                            Name = "Lagoonmaster",
                            RegDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "827-418-5289"
                        },
                        new
                        {
                            Uid = new Guid("9cdc0b8b-87ff-4331-bd83-ac1e00ec8a8a"),
                            Address = "53 Hickory Court Klamath Falls, OR 97603",
                            Name = "Shadecloud",
                            RegDate = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "629-202-6953"
                        },
                        new
                        {
                            Uid = new Guid("3fba17da-8e2b-4cd4-9692-ac1e00ec8a8a"),
                            Address = "8352 Marsh St. Indian Trail, NC 28079",
                            Name = "Pinnacle Aviation",
                            RegDate = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "937-490-6629"
                        },
                        new
                        {
                            Uid = new Guid("77b77f58-1487-4c25-bb33-ac1e00ec8a8a"),
                            Address = "9825 Pilgrim Ave. Ontario, CA 91762",
                            Name = "Neptune Solutions",
                            RegDate = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "713-210-5080"
                        },
                        new
                        {
                            Uid = new Guid("eeace729-abee-4982-be5c-ac1e00ec8a8a"),
                            Address = "2 Fordham Drive Merrick, NY 11566",
                            Name = "Night Networks",
                            RegDate = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "865-503-5762"
                        },
                        new
                        {
                            Uid = new Guid("42960bff-2eb9-4305-a512-ac1e00ec8a8a"),
                            Address = "292 Jones Lane Lanham, MD 20706",
                            Name = "Forestics",
                            RegDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "845-892-1111"
                        },
                        new
                        {
                            Uid = new Guid("b5bff7d5-2beb-4fd3-9f2f-ac1e00ec8a8a"),
                            Address = "91 Amerige Ave. Muscatine, IA 52761",
                            Name = "Bearings",
                            RegDate = new DateTime(2019, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "984-496-5436"
                        },
                        new
                        {
                            Uid = new Guid("032410ac-af50-4818-b4c9-ac1e00ec8a8a"),
                            Address = "788B Miles Ave. Fairport, NY 14450",
                            Name = "Mermedia",
                            RegDate = new DateTime(2019, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "905-246-2186"
                        },
                        new
                        {
                            Uid = new Guid("7ddb9506-e3b3-4044-8f2f-ac1e00ec8a8a"),
                            Address = "8403 Goldfield Ave. King Of Prussia, PA 19406",
                            Name = "Fairiprises",
                            RegDate = new DateTime(2019, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "519-259-6669"
                        },
                        new
                        {
                            Uid = new Guid("fa627a80-77b2-4eb2-866b-ac1e00ec8a8a"),
                            Address = "7507 Wakehurst Avenue Murfreesboro, TN 37128",
                            Name = "Mountaintime",
                            RegDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "801-871-4863"
                        },
                        new
                        {
                            Uid = new Guid("457d8223-f297-4a5d-bc9d-ac1e00ec8a8a"),
                            Address = "153 Old Lancaster Street Princeton, NJ 08540",
                            Name = "Fireworth",
                            RegDate = new DateTime(2019, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "264-712-5689"
                        },
                        new
                        {
                            Uid = new Guid("d9e18060-a9f8-49cc-8b82-ac1e00ec8a8a"),
                            Address = "108 Canterbury Avenue Reston, VA 20191",
                            Name = "Cloudworld",
                            RegDate = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "314-535-5117"
                        },
                        new
                        {
                            Uid = new Guid("c0418675-64b3-4dc0-8c55-ac1e00ec8a8a"),
                            Address = "932 Locust Ave. Minot, ND 58701",
                            Name = "Alp Arts",
                            RegDate = new DateTime(2020, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "542-361-0307"
                        },
                        new
                        {
                            Uid = new Guid("897aa125-268a-4488-9592-ac1e00ec8a8a"),
                            Address = "47 Glenridge Ave. Tupelo, MS 38801",
                            Name = "Timber Security",
                            RegDate = new DateTime(2020, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "744-230-2997"
                        });
                });

            modelBuilder.Entity("Test.Models.Invoice", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CompanyUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.HasIndex("CompanyUid");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("Test.Models.Invoice", b =>
                {
                    b.HasOne("Test.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
