// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Data;

namespace Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20200821182735_DataSeed-2")]
    partial class DataSeed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Models.Company", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("101688e0-4f0f-413f-b5f8-ac1e00ee4991"),
                            Address = "253 Fulton Circle Menasha, WI 54952",
                            Name = "Ecstatic Systems",
                            RegDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "431-393-0117"
                        },
                        new
                        {
                            Uid = new Guid("850d5807-5245-407d-b574-ac1e00ee4991"),
                            Address = "55 Shub Farm Court Yuma, AZ 85365",
                            Name = "Red Limited",
                            RegDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "887-738-4272"
                        },
                        new
                        {
                            Uid = new Guid("c3816c80-7df4-4cb7-8753-ac1e00ee4991"),
                            Address = "8863 Howard Court Traverse City, MI 49684",
                            Name = "Primal Electronics",
                            RegDate = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "909-467-1181"
                        },
                        new
                        {
                            Uid = new Guid("9e5ae151-0087-4e95-a2c8-ac1e00ee4991"),
                            Address = "813 Pheasant Street Huntley, IL 60142",
                            Name = "Surprisystems",
                            RegDate = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "558-663-2657"
                        },
                        new
                        {
                            Uid = new Guid("b07ec516-55c2-463c-93c0-ac1e00ee4991"),
                            Address = "5 Boston St. Patchogue, NY 11772",
                            Name = "Gorillacoustics",
                            RegDate = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "208-652-0972"
                        },
                        new
                        {
                            Uid = new Guid("fad4f78b-5e82-4f94-97ea-ac1e00ee4991"),
                            Address = "39 Jockey Hollow St. Passaic, NJ 07055",
                            Name = "Silver Linetworks",
                            RegDate = new DateTime(2019, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "754-934-6607"
                        },
                        new
                        {
                            Uid = new Guid("df25db09-8366-4760-b25c-ac1e00ee4991"),
                            Address = "8 Main St. Bridgeton, NJ 08302",
                            Name = "Dwarfoods",
                            RegDate = new DateTime(2019, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "428-213-6913"
                        },
                        new
                        {
                            Uid = new Guid("1cf6963d-f86f-45dd-b230-ac1e00ee4991"),
                            Address = "9801 Mammoth Drive Winston Salem, NC 27103",
                            Name = "Greenaid",
                            RegDate = new DateTime(2019, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "453-539-9934"
                        },
                        new
                        {
                            Uid = new Guid("bef90d68-db0c-4817-834e-ac1e00ee4991"),
                            Address = "49 Talbot Street Stroudsburg, PA 18360",
                            Name = "Squidwood",
                            RegDate = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "925-925-3730"
                        },
                        new
                        {
                            Uid = new Guid("621375b6-63ed-4455-a74c-ac1e00ee4991"),
                            Address = "7566 Hawthorne Drive Port Chester, NY 10573",
                            Name = "Thunderwares",
                            RegDate = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "922-481-4794"
                        },
                        new
                        {
                            Uid = new Guid("c8bb3057-8f3f-4487-9041-ac1e00ee4991"),
                            Address = "9337 East Dr. Meadville, PA 16335",
                            Name = "Tundra Brews",
                            RegDate = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "771-896-0645"
                        },
                        new
                        {
                            Uid = new Guid("9decf2aa-643c-4c89-b518-ac1e00ee4991"),
                            Address = "14 Academy Street Arlington, MA 02474",
                            Name = "Angel Systems",
                            RegDate = new DateTime(2019, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "374-323-7205"
                        },
                        new
                        {
                            Uid = new Guid("e9e8431e-4c76-4b4c-a2fa-ac1e00ee4991"),
                            Address = "8959 Pennsylvania Court Hoboken, NJ 07030",
                            Name = "Ecstatic Enterprises",
                            RegDate = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "992-452-6822"
                        },
                        new
                        {
                            Uid = new Guid("0114129a-d717-4b67-a45e-ac1e00ee4991"),
                            Address = "8501 James St. Southampton, PA 18966",
                            Name = "Starecords",
                            RegDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "798-594-7742"
                        },
                        new
                        {
                            Uid = new Guid("bfc00b6a-17ab-4fb8-85cc-ac1e00ee4991"),
                            Address = "9022 Branch St. Montgomery Village, MD 20886",
                            Name = "Apexi",
                            RegDate = new DateTime(2020, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "350-813-1923"
                        },
                        new
                        {
                            Uid = new Guid("3a7346c7-a436-4230-9f12-ac1e00ee4991"),
                            Address = "100 Old Oxford Ave. Norwich, CT 06360",
                            Name = "Galerprises",
                            RegDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "520-872-8810"
                        },
                        new
                        {
                            Uid = new Guid("e8942d77-af9b-49e3-869d-ac1e00ee4991"),
                            Address = "443 Gates Avenue Memphis, TN 38106",
                            Name = "Quaductions",
                            RegDate = new DateTime(2020, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "799-500-7874"
                        },
                        new
                        {
                            Uid = new Guid("07c7a0db-cf30-445e-ac19-ac1e00ee4991"),
                            Address = "85 Marlborough Dr. Zeeland, MI 49464",
                            Name = "Wavemedia",
                            RegDate = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "773-728-4669"
                        },
                        new
                        {
                            Uid = new Guid("f1fcb2a1-329c-45f2-8539-ac1e00ee4991"),
                            Address = "890 Wood Street Baltimore, MD 21206",
                            Name = "Pixywater",
                            RegDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "244-916-5331"
                        },
                        new
                        {
                            Uid = new Guid("f0bdb062-7210-4cc5-aad7-ac1e00ee4991"),
                            Address = "39 Tarkiln Hill St. West Hempstead, NY 11552",
                            Name = "Hoglight",
                            RegDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "392-458-6631"
                        },
                        new
                        {
                            Uid = new Guid("f16d6d80-437f-4477-9b70-ac1e00ee4991"),
                            Address = "8638 Santa Clara St. Yuba City, CA 95993",
                            Name = "Twilight Corporation",
                            RegDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "551-996-8865"
                        },
                        new
                        {
                            Uid = new Guid("8abbe925-5121-44c4-b632-ac1e00ee4991"),
                            Address = "506 South Gregory Lane Cumming, GA 30040",
                            Name = "Silver",
                            RegDate = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "467-454-5805"
                        },
                        new
                        {
                            Uid = new Guid("aef9dbfc-c319-491c-bc33-ac1e00ee4991"),
                            Address = "2 Howard Ave. Germantown, MD 20874",
                            Name = "Red Security",
                            RegDate = new DateTime(2020, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "931-970-0832"
                        },
                        new
                        {
                            Uid = new Guid("99f3c8b9-ff02-46d3-a3f8-ac1e00ee4991"),
                            Address = "580 N. Liberty Dr. Orange Park, FL 32065",
                            Name = "Chiefoods",
                            RegDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "975-663-2423"
                        },
                        new
                        {
                            Uid = new Guid("008735c9-e943-4ab5-961e-ac1e00ee4991"),
                            Address = "9459 North Mill Ave. Roanoke Rapids, NC 27870",
                            Name = "Essensecurity",
                            RegDate = new DateTime(2020, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "966-722-2521"
                        },
                        new
                        {
                            Uid = new Guid("ade2714c-2d33-4ea1-ac5e-ac1e00ee4991"),
                            Address = "543 White Drive New Bedford, MA 02740",
                            Name = "Elitelligence",
                            RegDate = new DateTime(2018, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "606-752-7843"
                        },
                        new
                        {
                            Uid = new Guid("34397675-6bf9-400b-9da4-ac1e00ee4991"),
                            Address = "96 Armstrong Lane Cary, NC 27511",
                            Name = "Daydreamotors",
                            RegDate = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "838-383-3934"
                        },
                        new
                        {
                            Uid = new Guid("b256e609-6012-400a-93bb-ac1e00ee4991"),
                            Address = "8561 Glen Eagles Circle Natick, MA 01760",
                            Name = "Heartstone",
                            RegDate = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "509-760-3953"
                        },
                        new
                        {
                            Uid = new Guid("88c4b86f-7a05-436e-af50-ac1e00ee4991"),
                            Address = "37 East Logan Lane Eugene, OR 97402",
                            Name = "Lagoonmaster",
                            RegDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "827-418-5289"
                        },
                        new
                        {
                            Uid = new Guid("00069eff-f06a-4fba-989a-ac1e00ee4991"),
                            Address = "53 Hickory Court Klamath Falls, OR 97603",
                            Name = "Shadecloud",
                            RegDate = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "629-202-6953"
                        },
                        new
                        {
                            Uid = new Guid("e0662284-b617-49cd-9eb8-ac1e00ee4991"),
                            Address = "8352 Marsh St. Indian Trail, NC 28079",
                            Name = "Pinnacle Aviation",
                            RegDate = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "937-490-6629"
                        },
                        new
                        {
                            Uid = new Guid("755d3851-47ee-4d2a-bf4d-ac1e00ee4991"),
                            Address = "9825 Pilgrim Ave. Ontario, CA 91762",
                            Name = "Neptune Solutions",
                            RegDate = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "713-210-5080"
                        },
                        new
                        {
                            Uid = new Guid("e4f84719-6849-4f58-988a-ac1e00ee4991"),
                            Address = "2 Fordham Drive Merrick, NY 11566",
                            Name = "Night Networks",
                            RegDate = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "865-503-5762"
                        },
                        new
                        {
                            Uid = new Guid("ad3aa4cc-58b0-4bd3-b190-ac1e00ee4991"),
                            Address = "292 Jones Lane Lanham, MD 20706",
                            Name = "Forestics",
                            RegDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "845-892-1111"
                        },
                        new
                        {
                            Uid = new Guid("30ad9ae1-017c-4f0b-bfab-ac1e00ee4991"),
                            Address = "91 Amerige Ave. Muscatine, IA 52761",
                            Name = "Bearings",
                            RegDate = new DateTime(2019, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "984-496-5436"
                        },
                        new
                        {
                            Uid = new Guid("810b3ebc-ee24-4e7b-a748-ac1e00ee4991"),
                            Address = "788B Miles Ave. Fairport, NY 14450",
                            Name = "Mermedia",
                            RegDate = new DateTime(2019, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "905-246-2186"
                        },
                        new
                        {
                            Uid = new Guid("8acb451d-07ed-4c9f-8711-ac1e00ee4991"),
                            Address = "8403 Goldfield Ave. King Of Prussia, PA 19406",
                            Name = "Fairiprises",
                            RegDate = new DateTime(2019, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "519-259-6669"
                        },
                        new
                        {
                            Uid = new Guid("180fbe87-0ef6-4532-b16e-ac1e00ee4991"),
                            Address = "7507 Wakehurst Avenue Murfreesboro, TN 37128",
                            Name = "Mountaintime",
                            RegDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "801-871-4863"
                        },
                        new
                        {
                            Uid = new Guid("811322f2-4156-4227-ac04-ac1e00ee4991"),
                            Address = "153 Old Lancaster Street Princeton, NJ 08540",
                            Name = "Fireworth",
                            RegDate = new DateTime(2019, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "264-712-5689"
                        },
                        new
                        {
                            Uid = new Guid("c40a1ed2-6000-48cf-9a19-ac1e00ee4991"),
                            Address = "108 Canterbury Avenue Reston, VA 20191",
                            Name = "Cloudworld",
                            RegDate = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "314-535-5117"
                        },
                        new
                        {
                            Uid = new Guid("638acb5b-7e09-46f4-b1be-ac1e00ee4991"),
                            Address = "932 Locust Ave. Minot, ND 58701",
                            Name = "Alp Arts",
                            RegDate = new DateTime(2020, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "542-361-0307"
                        },
                        new
                        {
                            Uid = new Guid("e78dc0b3-7aa5-41ac-bb42-ac1e00ee4991"),
                            Address = "47 Glenridge Ave. Tupelo, MS 38801",
                            Name = "Timber Security",
                            RegDate = new DateTime(2020, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "744-230-2997"
                        });
                });

            modelBuilder.Entity("Test.Models.Invoice", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CompanyUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.HasIndex("CompanyUid");

                    b.ToTable("Invoice");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("6a66871b-fc8a-4c48-b63a-ac1e00ee4991"),
                            CompanyUid = new Guid("101688e0-4f0f-413f-b5f8-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-23-00-01",
                            Total = 34300.040000000001,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("a38d407f-32d3-4db2-b01d-ac1e00ee4991"),
                            CompanyUid = new Guid("850d5807-5245-407d-b574-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-28-00-02",
                            Total = 15690.59,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("9aae4c30-d520-4fb9-8ea9-ac1e00ee4991"),
                            CompanyUid = new Guid("c3816c80-7df4-4cb7-8753-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-31-00-03",
                            Total = 298.36000000000001,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("710ddf22-f2fd-490f-bd5a-ac1e00ee4991"),
                            CompanyUid = new Guid("9e5ae151-0087-4e95-a2c8-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-02-21-00-04",
                            Total = 1431.4300000000001,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("13c9df37-7bcd-4430-ab03-ac1e00ee4991"),
                            CompanyUid = new Guid("b07ec516-55c2-463c-93c0-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-03-31-00-05",
                            Total = 18186.209999999999,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("0555e299-2b12-4e67-b599-ac1e00ee4991"),
                            CompanyUid = new Guid("fad4f78b-5e82-4f94-97ea-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-04-17-00-06",
                            Total = 4909.3299999999999,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("2d8b60ca-326f-43b1-a193-ac1e00ee4991"),
                            CompanyUid = new Guid("df25db09-8366-4760-b25c-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-15-00-07",
                            Total = 39931.110000000001,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("cda834ff-0a32-4fc4-8ffc-ac1e00ee4991"),
                            CompanyUid = new Guid("1cf6963d-f86f-45dd-b230-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-21-00-08",
                            Total = 28254.93,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("acd8b3a6-2826-4c6b-b9e1-ac1e00ee4991"),
                            CompanyUid = new Guid("bef90d68-db0c-4817-834e-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-22-00-09",
                            Total = 44787.620000000003,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("6ffae802-87f7-4c11-88d6-ac1e00ee4991"),
                            CompanyUid = new Guid("621375b6-63ed-4455-a74c-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-26-00-10",
                            Total = 22502.970000000001,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("18e50bf2-4d0b-43ca-b869-ac1e00ee4991"),
                            CompanyUid = new Guid("c8bb3057-8f3f-4487-9041-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-01-00-11",
                            Total = 4945.6999999999998,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("6a6ca82c-d39b-4638-93d1-ac1e00ee4991"),
                            CompanyUid = new Guid("9decf2aa-643c-4c89-b518-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-03-00-12",
                            Total = 36277.519999999997,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("0a6103a5-5bb2-4f4d-823d-ac1e00ee4991"),
                            CompanyUid = new Guid("e9e8431e-4c76-4b4c-a2fa-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-11-00-13",
                            Total = 23971.299999999999,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("c607e13b-d6e8-4563-b439-ac1e00ee4991"),
                            CompanyUid = new Guid("0114129a-d717-4b67-a45e-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-23-00-14",
                            Total = 46565.209999999999,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("9bcd465c-c954-47cd-8c81-ac1e00ee4991"),
                            CompanyUid = new Guid("bfc00b6a-17ab-4fb8-85cc-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-03-00-15",
                            Total = 38232.68,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("6f9f4597-22d7-46c0-a7ce-ac1e00ee4991"),
                            CompanyUid = new Guid("3a7346c7-a436-4230-9f12-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-24-00-16",
                            Total = 27786.68,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("44a4ab53-e178-4489-97c5-ac1e00ee4991"),
                            CompanyUid = new Guid("e8942d77-af9b-49e3-869d-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-08-00-17",
                            Total = 22732.68,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("910788f9-b08f-453e-804f-ac1e00ee4991"),
                            CompanyUid = new Guid("07c7a0db-cf30-445e-ac19-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-22-00-18",
                            Total = 43822.839999999997,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("a74e01cc-d483-473a-addc-ac1e00ee4991"),
                            CompanyUid = new Guid("f1fcb2a1-329c-45f2-8539-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-10-01-00-19",
                            Total = 15328.68,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("4ca87c7e-90b0-48fe-b449-ac1e00ee4991"),
                            CompanyUid = new Guid("f0bdb062-7210-4cc5-aad7-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-10-22-00-20",
                            Total = 48152.279999999999,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("0b55a74f-4400-48a1-aeac-ac1e00ee4991"),
                            CompanyUid = new Guid("f16d6d80-437f-4477-9b70-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-11-26-00-21",
                            Total = 14065.1,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("898c95a7-827c-45ff-85ba-ac1e00ee4991"),
                            CompanyUid = new Guid("8abbe925-5121-44c4-b632-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-11-27-00-22",
                            Total = 37993.709999999999,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("200faca3-d7c2-4a83-9e62-ac1e00ee4991"),
                            CompanyUid = new Guid("aef9dbfc-c319-491c-bc33-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-11-30-00-23",
                            Total = 38244.32,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("09c01a6a-095d-4bb7-8fce-ac1e00ee4991"),
                            CompanyUid = new Guid("99f3c8b9-ff02-46d3-a3f8-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-12-02-00-24",
                            Total = 27489.400000000001,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("1f36119b-de53-4a6b-bfde-ac1e00ee4991"),
                            CompanyUid = new Guid("008735c9-e943-4ab5-961e-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-12-22-00-25",
                            Total = 14378.530000000001,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("056554c8-3d80-45dd-9a2f-ac1e00ee4991"),
                            CompanyUid = new Guid("ade2714c-2d33-4ea1-ac5e-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-31-00-26",
                            Total = 45954.989999999998,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("8668b7cd-be2a-4a69-8b71-ac1e00ee4991"),
                            CompanyUid = new Guid("34397675-6bf9-400b-9da4-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-02-06-00-27",
                            Total = 47950.589999999997,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("30428905-9f60-40cb-b66a-ac1e00ee4991"),
                            CompanyUid = new Guid("b256e609-6012-400a-93bb-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-02-21-00-28",
                            Total = 15495.889999999999,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("d190bfe1-f92a-48a5-be3e-ac1e00ee4991"),
                            CompanyUid = new Guid("88c4b86f-7a05-436e-af50-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-03-23-00-29",
                            Total = 25963.68,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("c8366444-7108-4ccb-8ccf-ac1e00ee4991"),
                            CompanyUid = new Guid("00069eff-f06a-4fba-989a-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-04-17-00-30",
                            Total = 27774.66,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("754c32a8-572c-4005-b3c6-ac1e00ee4991"),
                            CompanyUid = new Guid("e0662284-b617-49cd-9eb8-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-01-00-31",
                            Total = 36187.620000000003,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("fc9349ce-117b-47e6-9bb3-ac1e00ee4991"),
                            CompanyUid = new Guid("755d3851-47ee-4d2a-bf4d-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-29-00-32",
                            Total = 29825.919999999998,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("b80ef115-901e-4b0c-8aac-ac1e00ee4991"),
                            CompanyUid = new Guid("e4f84719-6849-4f58-988a-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-02-00-33",
                            Total = 4298.6300000000001,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("a782e8d6-60e9-45d1-b1c9-ac1e00ee4991"),
                            CompanyUid = new Guid("ad3aa4cc-58b0-4bd3-b190-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-06-00-34",
                            Total = 43305.220000000001,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("dde6c022-6bf8-4c9b-8ce0-ac1e00ee4991"),
                            CompanyUid = new Guid("30ad9ae1-017c-4f0b-bfab-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-15-00-35",
                            Total = 46484.260000000002,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("14a70f1d-67b3-4aed-b740-ac1e00ee4991"),
                            CompanyUid = new Guid("810b3ebc-ee24-4e7b-a748-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-20-00-36",
                            Total = 47141.389999999999,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("29b41beb-b9fe-4f6a-840c-ac1e00ee4991"),
                            CompanyUid = new Guid("8acb451d-07ed-4c9f-8711-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-23-00-37",
                            Total = 2787.27,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("d0f0b8a0-6d47-4108-9107-ac1e00ee4991"),
                            CompanyUid = new Guid("180fbe87-0ef6-4532-b16e-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-24-00-38",
                            Total = 49818.980000000003,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("1c755929-f048-426d-b1f3-ac1e00ee4991"),
                            CompanyUid = new Guid("811322f2-4156-4227-ac04-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-05-00-39",
                            Total = 45908.629999999997,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("c7fea5b3-34a8-490d-81b4-ac1e00ee4991"),
                            CompanyUid = new Guid("c40a1ed2-6000-48cf-9a19-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-27-00-40",
                            Total = 18576.209999999999,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("e20042c3-ce3f-4e83-90c1-ac1e00ee4991"),
                            CompanyUid = new Guid("638acb5b-7e09-46f4-b1be-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-02-00-41",
                            Total = 31128.419999999998,
                            Type = 0
                        },
                        new
                        {
                            Uid = new Guid("92016a86-9a1d-458c-82b5-ac1e00ee4991"),
                            CompanyUid = new Guid("e78dc0b3-7aa5-41ac-bb42-ac1e00ee4991"),
                            InvDate = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-15-00-42",
                            Total = 14540.690000000001,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Test.Models.Invoice", b =>
                {
                    b.HasOne("Test.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
