// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Data;

namespace Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Models.Company", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("bec4b907-9505-4a97-aea1-ac1f00bbb009"),
                            Address = "253 Fulton Circle Menasha, WI 54952",
                            Name = "Ecstatic Systems",
                            RegDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "431-393-0117"
                        },
                        new
                        {
                            Uid = new Guid("11313bda-2121-4e3e-b59e-ac1f00bbb009"),
                            Address = "55 Shub Farm Court Yuma, AZ 85365",
                            Name = "Red Limited",
                            RegDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "887-738-4272"
                        },
                        new
                        {
                            Uid = new Guid("6d44633d-9895-4c78-a67d-ac1f00bbb009"),
                            Address = "8863 Howard Court Traverse City, MI 49684",
                            Name = "Primal Electronics",
                            RegDate = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "909-467-1181"
                        },
                        new
                        {
                            Uid = new Guid("176e0d47-8811-48c9-ad22-ac1f00bbb009"),
                            Address = "813 Pheasant Street Huntley, IL 60142",
                            Name = "Surprisystems",
                            RegDate = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "558-663-2657"
                        },
                        new
                        {
                            Uid = new Guid("4bef8e19-6cad-4806-a8f2-ac1f00bbb009"),
                            Address = "5 Boston St. Patchogue, NY 11772",
                            Name = "Gorillacoustics",
                            RegDate = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "208-652-0972"
                        },
                        new
                        {
                            Uid = new Guid("ab6a6355-ef25-4768-8941-ac1f00bbb009"),
                            Address = "39 Jockey Hollow St. Passaic, NJ 07055",
                            Name = "Silver Linetworks",
                            RegDate = new DateTime(2019, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "754-934-6607"
                        },
                        new
                        {
                            Uid = new Guid("f427d261-d1c9-49f4-ac2c-ac1f00bbb009"),
                            Address = "8 Main St. Bridgeton, NJ 08302",
                            Name = "Dwarfoods",
                            RegDate = new DateTime(2019, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "428-213-6913"
                        },
                        new
                        {
                            Uid = new Guid("4394e2fe-8671-48cd-8ffc-ac1f00bbb009"),
                            Address = "9801 Mammoth Drive Winston Salem, NC 27103",
                            Name = "Greenaid",
                            RegDate = new DateTime(2019, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "453-539-9934"
                        },
                        new
                        {
                            Uid = new Guid("3c1dd2b8-51d2-47fb-a2b6-ac1f00bbb009"),
                            Address = "49 Talbot Street Stroudsburg, PA 18360",
                            Name = "Squidwood",
                            RegDate = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "925-925-3730"
                        },
                        new
                        {
                            Uid = new Guid("310ed3a1-eafb-408c-8878-ac1f00bbb009"),
                            Address = "7566 Hawthorne Drive Port Chester, NY 10573",
                            Name = "Thunderwares",
                            RegDate = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "922-481-4794"
                        },
                        new
                        {
                            Uid = new Guid("c475bb2d-e032-425a-9ffc-ac1f00bbb009"),
                            Address = "9337 East Dr. Meadville, PA 16335",
                            Name = "Tundra Brews",
                            RegDate = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "771-896-0645"
                        },
                        new
                        {
                            Uid = new Guid("5e442f90-8c41-4556-91bd-ac1f00bbb009"),
                            Address = "14 Academy Street Arlington, MA 02474",
                            Name = "Angel Systems",
                            RegDate = new DateTime(2019, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "374-323-7205"
                        },
                        new
                        {
                            Uid = new Guid("68d90a05-e6c7-4888-99f4-ac1f00bbb009"),
                            Address = "8959 Pennsylvania Court Hoboken, NJ 07030",
                            Name = "Ecstatic Enterprises",
                            RegDate = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "992-452-6822"
                        },
                        new
                        {
                            Uid = new Guid("7724a338-3766-49f9-9880-ac1f00bbb009"),
                            Address = "8501 James St. Southampton, PA 18966",
                            Name = "Starecords",
                            RegDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "798-594-7742"
                        },
                        new
                        {
                            Uid = new Guid("694fabf4-86ba-483c-a906-ac1f00bbb009"),
                            Address = "9022 Branch St. Montgomery Village, MD 20886",
                            Name = "Apexi",
                            RegDate = new DateTime(2020, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "350-813-1923"
                        },
                        new
                        {
                            Uid = new Guid("8f0f085f-1293-455d-baa6-ac1f00bbb009"),
                            Address = "100 Old Oxford Ave. Norwich, CT 06360",
                            Name = "Galerprises",
                            RegDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "520-872-8810"
                        },
                        new
                        {
                            Uid = new Guid("6d825680-aa25-4f5b-8b47-ac1f00bbb009"),
                            Address = "443 Gates Avenue Memphis, TN 38106",
                            Name = "Quaductions",
                            RegDate = new DateTime(2020, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "799-500-7874"
                        },
                        new
                        {
                            Uid = new Guid("4f8859ed-46c0-441a-9676-ac1f00bbb009"),
                            Address = "85 Marlborough Dr. Zeeland, MI 49464",
                            Name = "Wavemedia",
                            RegDate = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "773-728-4669"
                        },
                        new
                        {
                            Uid = new Guid("827a2189-ebe1-4d99-9ca3-ac1f00bbb009"),
                            Address = "890 Wood Street Baltimore, MD 21206",
                            Name = "Pixywater",
                            RegDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "244-916-5331"
                        },
                        new
                        {
                            Uid = new Guid("1e57d26e-54df-4edc-bc8b-ac1f00bbb009"),
                            Address = "39 Tarkiln Hill St. West Hempstead, NY 11552",
                            Name = "Hoglight",
                            RegDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "392-458-6631"
                        },
                        new
                        {
                            Uid = new Guid("c59cf694-c845-4229-8f61-ac1f00bbb009"),
                            Address = "8638 Santa Clara St. Yuba City, CA 95993",
                            Name = "Twilight Corporation",
                            RegDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "551-996-8865"
                        },
                        new
                        {
                            Uid = new Guid("165288ad-8033-4222-880f-ac1f00bbb009"),
                            Address = "506 South Gregory Lane Cumming, GA 30040",
                            Name = "Silver",
                            RegDate = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "467-454-5805"
                        },
                        new
                        {
                            Uid = new Guid("1559968b-44c8-4119-95a7-ac1f00bbb009"),
                            Address = "2 Howard Ave. Germantown, MD 20874",
                            Name = "Red Security",
                            RegDate = new DateTime(2020, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "931-970-0832"
                        },
                        new
                        {
                            Uid = new Guid("fb5f44e4-2479-43a2-aea9-ac1f00bbb009"),
                            Address = "580 N. Liberty Dr. Orange Park, FL 32065",
                            Name = "Chiefoods",
                            RegDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "975-663-2423"
                        },
                        new
                        {
                            Uid = new Guid("962c48d7-230c-4c35-9a3f-ac1f00bbb009"),
                            Address = "9459 North Mill Ave. Roanoke Rapids, NC 27870",
                            Name = "Essensecurity",
                            RegDate = new DateTime(2020, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "966-722-2521"
                        },
                        new
                        {
                            Uid = new Guid("54899eb6-5650-4c09-9ec0-ac1f00bbb009"),
                            Address = "543 White Drive New Bedford, MA 02740",
                            Name = "Elitelligence",
                            RegDate = new DateTime(2018, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "606-752-7843"
                        },
                        new
                        {
                            Uid = new Guid("d9c6e3e5-3ee8-418e-85c7-ac1f00bbb009"),
                            Address = "96 Armstrong Lane Cary, NC 27511",
                            Name = "Daydreamotors",
                            RegDate = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "838-383-3934"
                        },
                        new
                        {
                            Uid = new Guid("653e47eb-eb3b-466b-84da-ac1f00bbb009"),
                            Address = "8561 Glen Eagles Circle Natick, MA 01760",
                            Name = "Heartstone",
                            RegDate = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "509-760-3953"
                        },
                        new
                        {
                            Uid = new Guid("9fed7294-b660-40db-b2df-ac1f00bbb009"),
                            Address = "37 East Logan Lane Eugene, OR 97402",
                            Name = "Lagoonmaster",
                            RegDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "827-418-5289"
                        },
                        new
                        {
                            Uid = new Guid("a3b9b638-c53d-42d6-8bb5-ac1f00bbb009"),
                            Address = "53 Hickory Court Klamath Falls, OR 97603",
                            Name = "Shadecloud",
                            RegDate = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "629-202-6953"
                        },
                        new
                        {
                            Uid = new Guid("8dc6f39b-b773-44c3-bf0f-ac1f00bbb009"),
                            Address = "8352 Marsh St. Indian Trail, NC 28079",
                            Name = "Pinnacle Aviation",
                            RegDate = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "937-490-6629"
                        },
                        new
                        {
                            Uid = new Guid("c1460df1-1ab8-4a2f-817c-ac1f00bbb009"),
                            Address = "9825 Pilgrim Ave. Ontario, CA 91762",
                            Name = "Neptune Solutions",
                            RegDate = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "713-210-5080"
                        },
                        new
                        {
                            Uid = new Guid("067bf585-3ca3-4fc2-8b7d-ac1f00bbb009"),
                            Address = "2 Fordham Drive Merrick, NY 11566",
                            Name = "Night Networks",
                            RegDate = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "865-503-5762"
                        },
                        new
                        {
                            Uid = new Guid("491a3e58-ed02-48e3-a1ab-ac1f00bbb009"),
                            Address = "292 Jones Lane Lanham, MD 20706",
                            Name = "Forestics",
                            RegDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "845-892-1111"
                        },
                        new
                        {
                            Uid = new Guid("4f02a711-485a-4382-b48c-ac1f00bbb009"),
                            Address = "91 Amerige Ave. Muscatine, IA 52761",
                            Name = "Bearings",
                            RegDate = new DateTime(2019, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "984-496-5436"
                        },
                        new
                        {
                            Uid = new Guid("8fea9c3d-5c0c-4c6a-9a54-ac1f00bbb009"),
                            Address = "788B Miles Ave. Fairport, NY 14450",
                            Name = "Mermedia",
                            RegDate = new DateTime(2019, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "905-246-2186"
                        },
                        new
                        {
                            Uid = new Guid("9b8bc3e9-6e90-4a12-b790-ac1f00bbb009"),
                            Address = "8403 Goldfield Ave. King Of Prussia, PA 19406",
                            Name = "Fairiprises",
                            RegDate = new DateTime(2019, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "519-259-6669"
                        },
                        new
                        {
                            Uid = new Guid("b31d01e0-df72-47c6-b561-ac1f00bbb009"),
                            Address = "7507 Wakehurst Avenue Murfreesboro, TN 37128",
                            Name = "Mountaintime",
                            RegDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "801-871-4863"
                        },
                        new
                        {
                            Uid = new Guid("d6c18bb0-de97-48b3-a44a-ac1f00bbb009"),
                            Address = "153 Old Lancaster Street Princeton, NJ 08540",
                            Name = "Fireworth",
                            RegDate = new DateTime(2019, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "264-712-5689"
                        },
                        new
                        {
                            Uid = new Guid("02623926-45c4-4a7a-881a-ac1f00bbb009"),
                            Address = "108 Canterbury Avenue Reston, VA 20191",
                            Name = "Cloudworld",
                            RegDate = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "314-535-5117"
                        },
                        new
                        {
                            Uid = new Guid("fd4789a5-fe5b-405a-8e5e-ac1f00bbb009"),
                            Address = "932 Locust Ave. Minot, ND 58701",
                            Name = "Alp Arts",
                            RegDate = new DateTime(2020, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "542-361-0307"
                        },
                        new
                        {
                            Uid = new Guid("44b725f8-c227-459b-94cc-ac1f00bbb009"),
                            Address = "47 Glenridge Ave. Tupelo, MS 38801",
                            Name = "Timber Security",
                            RegDate = new DateTime(2020, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telephone = "744-230-2997"
                        });
                });

            modelBuilder.Entity("Test.Models.Invoice", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CompanyUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.HasIndex("CompanyUid");

                    b.ToTable("Invoice");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("996c6e37-590f-4612-ad73-ac1f00bbb00a"),
                            CompanyUid = new Guid("bec4b907-9505-4a97-aea1-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-23-00-01",
                            Total = 34300.040000000001,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("df7d7988-ff50-46ab-ae9c-ac1f00bbb00a"),
                            CompanyUid = new Guid("11313bda-2121-4e3e-b59e-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-28-00-02",
                            Total = 15690.59,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("1f4a9ed3-14f5-4ef2-b7c5-ac1f00bbb00a"),
                            CompanyUid = new Guid("6d44633d-9895-4c78-a67d-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-31-00-03",
                            Total = 298.36000000000001,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("7af2f905-f4a8-4383-be37-ac1f00bbb00a"),
                            CompanyUid = new Guid("176e0d47-8811-48c9-ad22-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-02-21-00-04",
                            Total = 1431.4300000000001,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("da790ffe-3a7c-46df-9cb1-ac1f00bbb00a"),
                            CompanyUid = new Guid("4bef8e19-6cad-4806-a8f2-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-03-31-00-05",
                            Total = 18186.209999999999,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("f975f8ca-415b-445f-8c79-ac1f00bbb00a"),
                            CompanyUid = new Guid("ab6a6355-ef25-4768-8941-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-04-17-00-06",
                            Total = 4909.3299999999999,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("97e455e6-6fdf-4ba0-8c66-ac1f00bbb00a"),
                            CompanyUid = new Guid("f427d261-d1c9-49f4-ac2c-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-15-00-07",
                            Total = 39931.110000000001,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("5a067ce3-4a97-4e33-8ad6-ac1f00bbb00a"),
                            CompanyUid = new Guid("4394e2fe-8671-48cd-8ffc-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-21-00-08",
                            Total = 28254.93,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("2c5e4ddd-5712-4284-9ea6-ac1f00bbb00a"),
                            CompanyUid = new Guid("3c1dd2b8-51d2-47fb-a2b6-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-22-00-09",
                            Total = 44787.620000000003,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("26c5a25e-306c-4696-b0b1-ac1f00bbb00a"),
                            CompanyUid = new Guid("310ed3a1-eafb-408c-8878-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-26-00-10",
                            Total = 22502.970000000001,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("d3418a6e-50cf-4a0e-b921-ac1f00bbb00a"),
                            CompanyUid = new Guid("c475bb2d-e032-425a-9ffc-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-01-00-11",
                            Total = 4945.6999999999998,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("527d3e49-68c8-49a2-832e-ac1f00bbb00a"),
                            CompanyUid = new Guid("5e442f90-8c41-4556-91bd-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-03-00-12",
                            Total = 36277.519999999997,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("e4c34074-cdbd-4dd6-b393-ac1f00bbb00a"),
                            CompanyUid = new Guid("68d90a05-e6c7-4888-99f4-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-11-00-13",
                            Total = 23971.299999999999,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("7b7a2658-6a55-431f-8523-ac1f00bbb00a"),
                            CompanyUid = new Guid("7724a338-3766-49f9-9880-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-23-00-14",
                            Total = 46565.209999999999,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("937fb1b5-7c77-40f3-8cae-ac1f00bbb00a"),
                            CompanyUid = new Guid("694fabf4-86ba-483c-a906-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-03-00-15",
                            Total = 38232.68,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("0e78a19c-29d0-45a4-aa6c-ac1f00bbb00a"),
                            CompanyUid = new Guid("8f0f085f-1293-455d-baa6-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-24-00-16",
                            Total = 27786.68,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("412d6ae4-8033-48b7-aa76-ac1f00bbb00a"),
                            CompanyUid = new Guid("6d825680-aa25-4f5b-8b47-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-08-00-17",
                            Total = 22732.68,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("a8f93ca3-70d4-45cf-856c-ac1f00bbb00a"),
                            CompanyUid = new Guid("4f8859ed-46c0-441a-9676-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-22-00-18",
                            Total = 43822.839999999997,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("01ff5ea9-373c-48d3-b277-ac1f00bbb00a"),
                            CompanyUid = new Guid("827a2189-ebe1-4d99-9ca3-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-10-01-00-19",
                            Total = 15328.68,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("f789a5af-c1c1-4943-9eb9-ac1f00bbb00a"),
                            CompanyUid = new Guid("1e57d26e-54df-4edc-bc8b-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-10-22-00-20",
                            Total = 48152.279999999999,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("95235176-02a3-45ec-a4ee-ac1f00bbb00a"),
                            CompanyUid = new Guid("c59cf694-c845-4229-8f61-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-11-26-00-21",
                            Total = 14065.1,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("b259a500-3fdc-4643-aaad-ac1f00bbb00a"),
                            CompanyUid = new Guid("165288ad-8033-4222-880f-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-11-27-00-22",
                            Total = 37993.709999999999,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("e6d2945c-897b-42af-aee8-ac1f00bbb00a"),
                            CompanyUid = new Guid("1559968b-44c8-4119-95a7-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-11-30-00-23",
                            Total = 38244.32,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("84b617eb-c19a-4bef-8515-ac1f00bbb00a"),
                            CompanyUid = new Guid("fb5f44e4-2479-43a2-aea9-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-12-02-00-24",
                            Total = 27489.400000000001,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("24f883e2-033b-40df-ad58-ac1f00bbb00a"),
                            CompanyUid = new Guid("962c48d7-230c-4c35-9a3f-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-12-22-00-25",
                            Total = 14378.530000000001,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("0921c380-917c-467a-9c15-ac1f00bbb00a"),
                            CompanyUid = new Guid("54899eb6-5650-4c09-9ec0-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-01-31-00-26",
                            Total = 45954.989999999998,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("8e5fc0c9-f295-4344-b7f1-ac1f00bbb00a"),
                            CompanyUid = new Guid("d9c6e3e5-3ee8-418e-85c7-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-02-06-00-27",
                            Total = 47950.589999999997,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("9f8db1a5-8098-4626-9a16-ac1f00bbb00a"),
                            CompanyUid = new Guid("653e47eb-eb3b-466b-84da-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-02-21-00-28",
                            Total = 15495.889999999999,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("c07f53ba-1fd1-4d08-a1b7-ac1f00bbb00a"),
                            CompanyUid = new Guid("9fed7294-b660-40db-b2df-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-03-23-00-29",
                            Total = 25963.68,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("5cfe81f8-cbca-4c1b-ad02-ac1f00bbb00a"),
                            CompanyUid = new Guid("a3b9b638-c53d-42d6-8bb5-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-04-17-00-30",
                            Total = 27774.66,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("c8f33df1-5395-42cf-b379-ac1f00bbb00a"),
                            CompanyUid = new Guid("8dc6f39b-b773-44c3-bf0f-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-01-00-31",
                            Total = 36187.620000000003,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("991bbcbf-210c-47ed-a1aa-ac1f00bbb00a"),
                            CompanyUid = new Guid("c1460df1-1ab8-4a2f-817c-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-05-29-00-32",
                            Total = 29825.919999999998,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("78d2da43-cfc6-46d5-8974-ac1f00bbb00a"),
                            CompanyUid = new Guid("067bf585-3ca3-4fc2-8b7d-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-06-02-00-33",
                            Total = 4298.6300000000001,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("26689dd1-f69d-4fbc-9692-ac1f00bbb00a"),
                            CompanyUid = new Guid("491a3e58-ed02-48e3-a1ab-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-06-00-34",
                            Total = 43305.220000000001,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("5dacb8f4-1b08-497e-944a-ac1f00bbb00a"),
                            CompanyUid = new Guid("4f02a711-485a-4382-b48c-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-15-00-35",
                            Total = 46484.260000000002,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("2fb16d84-d8eb-4e95-90c3-ac1f00bbb00a"),
                            CompanyUid = new Guid("8fea9c3d-5c0c-4c6a-9a54-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-20-00-36",
                            Total = 47141.389999999999,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("6a4435da-ad9c-4d9f-b0f3-ac1f00bbb00a"),
                            CompanyUid = new Guid("9b8bc3e9-6e90-4a12-b790-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-23-00-37",
                            Total = 2787.27,
                            Type = 2
                        },
                        new
                        {
                            Uid = new Guid("20ca36a8-df6a-4f4d-9ad5-ac1f00bbb00a"),
                            CompanyUid = new Guid("b31d01e0-df72-47c6-b561-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-07-24-00-38",
                            Total = 49818.980000000003,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("5e2ec2f8-6bae-4fbb-9a8e-ac1f00bbb00a"),
                            CompanyUid = new Guid("d6c18bb0-de97-48b3-a44a-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-05-00-39",
                            Total = 45908.629999999997,
                            Type = 4
                        },
                        new
                        {
                            Uid = new Guid("8d17625b-609e-4aa2-8502-ac1f00bbb00a"),
                            CompanyUid = new Guid("02623926-45c4-4a7a-881a-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-08-27-00-40",
                            Total = 18576.209999999999,
                            Type = 1
                        },
                        new
                        {
                            Uid = new Guid("6c1192fe-fffb-4fec-985f-ac1f00bbb00a"),
                            CompanyUid = new Guid("fd4789a5-fe5b-405a-8e5e-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-02-00-41",
                            Total = 31128.419999999998,
                            Type = 3
                        },
                        new
                        {
                            Uid = new Guid("3b7ec842-def9-4648-b6da-ac1f00bbb00a"),
                            CompanyUid = new Guid("44b725f8-c227-459b-94cc-ac1f00bbb009"),
                            InvDate = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2020-09-15-00-42",
                            Total = 14540.690000000001,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Test.Models.Invoice", b =>
                {
                    b.HasOne("Test.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
